services:
  nginx:
    image: nginx:latest
    container_name: quint-felicity
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - webnet
      - phpnet

  php:
    image: ghcr.io/teaspoon-de/prod-php:latest
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    networks:
      - phpnet
      - dbnet

networks:
  webnet:
    external: false
  dbnet:
    external: false
  phpnet:
