services:
  nginx:
    image: nginx:latest
    container_name: quint-felicity
    environment:
      VIRTUAL_HOST: quint-felicity.de,www.quint-felicity.de
      LETSENCRYPT_HOST: quint-felicity.de,www.quint-felicity.de
      LETSENCRYPT_EMAIL: info@quint-felicity.de
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - webnet
      - phpnet

  php:
    image: ghcr.io/teaspoon-de/prod-php:latest
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    networks:
      - phpnet
      - dbnet

networks:
  webnet:
    external: true
  dbnet:
    external: true
  phpnet:
