services:
  nginx:
    image: nginx:latest
    container_name: quint-felicity
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - webnet
      - phpnet

  php:
    image: ghcr.io/teaspoon-de/prod-php:latest
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    networks:
      - phpnet
      - dbnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # das kann nicht sicher sein
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306" # unn√∂tog? gui geht prob eh nicht
    networks:
      - dbnet

networks:
  webnet:
    external: false
  dbnet:
    external: false
  phpnet:
